name: Type coverage and linting

on: [push, pull_request]

jobs:
  code_linting:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup python 3.9
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run isort
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
      
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      # - name: Annotate diff changes using reviewdog
      #   if: steps.action_black.outputs.is_formatted == 'true'
      #   uses: reviewdog/action-suggester@v1
      #   with:
      #     tool_name: blackfmt
